export { default as AboutUs } from './about/AboutUs'
export { default as ContactUs } from './contact/ContactUs'
export { default as FindProperties } from './findproperties/FindProperties'
export { default as Home } from './home/Home'
export { default as NotFound } from './notfound/NotFound'
export { default as Privacy } from './privacy/Privacy'
export { default as Products } from './products/Products'
export { default as TOS } from './tos/TOS'
